### PR TITLE
fix: pass index & children to deepMap, deepForeach & deepFind

### PR DESCRIPTION
**Pull request by dpinol**
Suggested implementation of #16

### CODE REVIEW

**Comment by fernandopasik** [comment]
I think your IDE is not using the prettier config or version that the repo has

**Comment by fernandopasik** [comment]
Sorry, I've verified that wasn't the case

**Comment by fernandopasik** [comment]
I think the same is happening for filter and deepFilter could you fix those as well?

**Comment by dpinol** [comment]
filter & deepFilter don't need any change because the filter function is directly passed to the Array filter function.
```
  return Children.toArray(children).filter(filterFn);

  return Children.toArray(children)
    .filter(deepFilterFn)

```

**Pull request merged**
